version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      timezone: Japan
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
