# Name of your application. Used to uniquely configure containers.
service: willnet_in

# Name of the container image.
image: willnet/willnet_in

# Deploy to these servers.
servers:
  web:
    hosts: 139.59.254.11
    labels:
      traefik.http.routers.willnet_in.rule: Host(`willnet.in`)
      traefik.http.routers.willnet_in.entrypoints: websecure
      traefik.http.routers.willnet_in.tls.certresolver: letsencrypt
      traefik.http.routers.www_willnet_in.rule: Host(`www.willnet.in`)
      traefik.http.routers.www_willnet_in.entrypoints: websecure
      traefik.http.routers.www_willnet_in.tls.certresolver: letsencrypt
registry:
  username: willnet
  password:
    - MRSK_REGISTRY_PASSWORD

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt:/letsencrypt"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "netwillnet@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

builder:
  multiarch: false

