service: willnet_in
image: willnet/willnet_in
proxy:
  app_port: 3000
  hosts:
    - willnet.in
    - www.willnet.in
  ssl: true
servers:
  - 139.59.254.11


registry:
  username: willnet
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= File.read('.ruby-version').strip %>

