name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ./vendor/bundle
          key: ${{ runner.os }}-deploy-v1-${{ hashFiles('Gemfile.lock') }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 227918278408.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Deploy
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3
        with:
          push: never
          env: |
            CI
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./bin/deploy
