name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ./vendor/bundle
          key: ${{ runner.os }}-deploy-v1-${{ hashFiles('Gemfile.lock') }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 227918278408.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: ghcr.io/willnet/willnet-in-devcontainer
          cacheFrom: ghcr.io/willnet/willnet-in-devcontainer
          env: |
            CI
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./bin/deploy
