name: zizmor

on:
  push:
  pull_request:

jobs:
  zizmor:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: woodruffw/zizmor-action@v1
